library/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
        url(r'^$', views.userprofile, name='userprofile-detail'),
        url(r'^userprofile/$', views.userprofile, name='userprofile-detail'),
        url(r'^categories/$', views.CategoryListView.as_view(), name='categories'),
        url(r'^category/(?P<slug>[^/]+)$', views.CategoryDetailView.as_view(), name='category-detail'),
        url(r'items/$', views.ItemListView.as_view(), name='items'),
        url(r'^item/(?P<pk>\d+)$', views.ItemDetailView.as_view(), name='item-detail'),
        url(r'^types/$', views.TypeListView.as_view(), name='types'),
        url(r'^languages/$', views.LanguageListView.as_view(), name='languages')
        ]

library/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse 
from django.utils import timezone
import uuid 


class ItemType(models.Model):

    name = models.CharField(max_length=35)

    def get_absolute_url(self):
        return reverse('type-detail', args=[str(self.name)])

    def __str__(self):
        return self.name


class ItemLanguage(models.Model):

    name = models.CharField(max_length=35)

    def get_absolute_url(self):
        return reverse('language-detail', args=[str(self.name)])

    def __str__(self):
        return self.name


class Category(models.Model):

    name = models.CharField(max_length=35)
    
    def get_absolute_url(self):
        return reverse('category-detail', args=[str(self.name)])

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'


class Item(models.Model):

    """

    basic model for scripts, commands, etc in library
    type, category, and language models 
    contributor is automatically populated when submitted by form

    """

    USER = 'User'
    IMHUSER = 'IMH-User'
    ROOT = 'Root'
    T1A = 'T1A'
    T1E = 'T1E'

    RUN_AS = (
            (USER, 'User'),
            (IMHUSER, 'IMH-User'),
            (ROOT, 'Root'),
            (T1A, 'Tier1Adv'),
            (T1E, 'T1e'),
            )

    name = models.CharField(max_length=100)
    contributor = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    category = models.ForeignKey('Category', blank=True, null=True)
    subcategory = models.ManyToManyField('Category', related_name='subcategory', blank=True, default=category)
    item_type = models.ForeignKey('ItemType', blank=True, null=True, on_delete=models.SET_NULL)
    language = models.ForeignKey('ItemLanguage', blank=True, null=True, on_delete=models.SET_NULL)
    text = models.TextField(blank=False, null=False)
    description = models.TextField(blank=False, null=False)
    location = models.CharField(max_length=100, blank=True, null=True)
    run_as = models.CharField(max_length=35, default=IMHUSER, choices=RUN_AS)
    reviewed = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('item-detail', args=[str(self.id)])

    def __str__(self):
        return self.name


## extension of django.contrib.auth built in User model
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    saved = models.ManyToManyField('Item')
    is_t1e = models.BooleanField(default=False)

    """
    def save_item(self, item):
        self.saved.add(item)
        self.save()

    def remove_item(self, item):
        self.saved.remove(item)
        self.save()

    def __str__(self):
        return self.user.get_username()
    """

class KBA(models.Model):
    
    """

    model for kbas related to script and command items
    would just be links to outside articles
    eventually maybe create seperate article model for internal kbas

    """

    url = models.CharField(max_length=250)
    category = models.ForeignKey('Category', blank=True, null=True)
    title = models.CharField(max_length=100)
    reviewed = models.BooleanField(default=False)
    related_item = models.ManyToManyField('Item')
    author = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.name

library/forms.py
from django import forms
from library.models import Item, Category, UserProfile


## basic form to add item
## shown on userprofile if user is member of Contributor group
## need to adjust for new fields in Item model
class ContributionForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = ['name', 'category', 'text', 'description', 'location']
        widgets = {
            'text': forms.Textarea(attrs={'rows':4, 'cols':40}),
            'description': forms.Textarea(attrs={'rows':4, 'cols':40})
            }


class SavedForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ['saved']

library/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views import generic
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from library.models import Item, Category, UserProfile, ItemLanguage, ItemType
from library.forms import ContributionForm, SavedForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User, Group


def add_saved(request):

    """
    view for ajax for save item button
    """
    pass


@login_required
def index(request):

    """
    eliminate 

    should be basic landing page but currently stats page
    the contents of this index function view should be moved
    to the sidebar
    """

    num_scripts = Item.objects.filter(reviewed=True).count()
    newest = Item.objects.filter(reviewed=True)[::-1][:5]
    #5 most used

    context = {
        'num_scripts': num_scripts,
        #'num_contributors': num_contributors,
        'newest': newest,
        }

    if Group.objects.filter(name='Contributor'):
        contributors = Group.objects.get(name='Contributor')
        num_contributors = contributors.user_set.count()
        context['num_contributors'] = num_contributors

    return render(request, 'library/index.html', context=context)


@login_required
def userprofile(request):

    """
    main view for logged in user

    includes contribution form if user is a member of 
    contributor group and a list of pending and reviewed
    items
    """

    username = request.user.get_username()
    if UserProfile.objects.filter(user=request.user):
        profile = UserProfile.objects.get(user=request.user)
    else:
        UserProfile.objects.create(
            user=request.user
            )
        profile = UserProfile.objects.get(user=request.user)
    contributions = Item.objects.filter(reviewed=True).filter(contributor=profile.user)
    new_contrib = Item.objects.filter(reviewed=True).filter(contributor=profile.user).order_by('-created')[:10]
    total_contributions = contributions.count()
    pending_contributions = Item.objects.filter(reviewed=False).filter(contributor=profile.user)
    pending_count = pending_contributions.count()
    saved_items = profile.saved
    saved_count = saved_items.count()

    ## form to contribute new item
    ## is added to pending list until reviewed by admin 
    if request.method == 'POST':
        contribution_form = ContributionForm(request.POST)
        if contribution_form.is_valid():
            item = Item.objects.create(
                name = contribution_form.cleaned_data.get('name'),
                contributor = request.user,
                category = contribution_form.cleaned_data.get('category'),
                text = contribution_form.cleaned_data.get('text'),
                description = contribution_form.cleaned_data.get('description'),
                location = contribution_form.cleaned_data.get('location'),
                )
            return HttpResponseRedirect(reverse('userprofile-detail'))
    else:
        contribution_form = ContributionForm()
    
    context = {
            'username': username,
            'new_contrib': new_contrib,
            'contributions': contributions,
            'total_contributions': total_contributions,
            'pending_contributions': pending_contributions,
            'pending_count': pending_count,
            'contribution_form': contribution_form,
            'saved_items': saved_items,
            'saved_count': saved_count,
            }

    return render(request, 'library/userprofile.html', context=context)


class ItemListView(LoginRequiredMixin, generic.ListView):
    template_name = 'library/items.html'
    model = Item


class ItemDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'library/item.html'
    model = Item


class CategoryListView(LoginRequiredMixin, generic.ListView):
    template_name = 'library/categories.html'
    model = Category

    """
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context[''] = 
        return context
    """


class CategoryDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'library/category.html'
    model = Category
    slug_field = 'name'


class LanguageListView(LoginRequiredMixin, generic.ListView):
    template_name = 'library/languages.html'
    model = ItemLanguage


class TypeListView(LoginRequiredMixin, generic.ListView):
    template_name = 'library/types.html'
    model = ItemType

templates/library/cat_menu.html
<div class="cat_menu">
  {% if category_list %}
  <ul class="cat_menu_list">
    {% for category in category_list %}
    <li class="cat_menu_item"><a href="#{{ category.name }}"><h5>{{ category.name }}</h5></a></li>
    {% endfor %}
  </ul>
  {% endif %}
</div>

templates/library/categories.html
{% extends "base_generic.html" %}

{% block content %}
  <h3>Categories</h3>
  {% if category_list %}
    {% for category in category_list %}
      <h4 id="{{ category.name }}"><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></h4>
      {% include "library/cat_menu.html" %}
      <ul>
      {% for item in category.item_set.all %}
      {% if item.reviewed %}
      <li>
       <a href="{% url 'item-detail' pk=item.id %}"><strong>{{ item }}</strong></a></br>
       <p class="code-block" id="{{ item.pk }}">{{ item.text }}</p>
       <button onclick="copyToClipboard('#{{ item.pk }}')">copy</button>
      </li>
      {% endif %}
      {% endfor %}
      </ul>
    {% endfor %}
  {% endif %}       
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script>
  function copyToClipboard(element) {
    var $temp = $("<textarea>");
    $("body").append($temp);
    $temp.val($(element).text()).select();
    document.execCommand("copy");
    $temp.remove();
  }
</script>

{% endblock %}

templates/library/category.html
{% extends "base_generic.html" %}

{% block content %}
<h3>{{ category.name }}</h3>
{% if category.item_set %}
<ul>
  {% for item in category.item_set.all %}
  {% if item.reviewed %}<li><a href="{% url 'item-detail' pk=item.id %}">{{ item }}</a></li>{% endif %}

  {% endfor %}
</ul>
{% endif %}
{% endblock %}

templates/library/contributor.html
{% extends "base_generic.html" %}

{% block content %}
  <h3>{{ contributor.username }}</h3>
  <p><strong>Contributions:</strong> {{ contributor.number_contributions }}</p>
  <ul>
    {% for item in contributor.contributions %}
      <li>{{ item }}</li>
    {% endfor %}
  </ul>
{% endblock %}

templates/library/contributors.html
{% extends "base_generic.html" %}

{% block content %}
  <h3>Contributors</h3>
  {% if contributor_list %}
  <ul>
    {% for contributor in contributor_list %}
      <li>
	      <a href="{{ contributor.get_absolute_url }}">{{ contributor.username }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
  <p>No Contributors.</p>
  {% endif %}       
{% endblock %}

templates/library/index.html
{% extends "base_generic.html" %}

{% block content %}
  <h5>Stats</h5>
  <ul>
    <li><strong>Scripts: </strong> {{ num_scripts  }}</li>
    {% if num_contributors %}<li><strong>Contributors: </strong> {{ num_contributors }}</li>{% endif %}
    <li><strong>Latest: </strong>
      {% if newest %}
      <ul>
      {% for item in newest %}
      {% if item.reviewed %}<li><a href="{% url 'item-detail' pk=item.id %}">{{ item.name }}</a></li>{% endif %}
      {% endfor %}
      </ul>
      {% endif %}
  </ul>
{% endblock %}

templates/library/item.html
{% extends "base_generic.html" %}

{% block content %}
  <h4>{{ item.name }}</h4>
  {% if item.contributor %}
  <p><strong>Contributor: </strong>{{item.contributor}}</p>
  {% endif %}
  <p><strong>Added: </strong> {{ item.created | date:"M d, Y" }}</p>
  <p><strong>Updated: </strong> {{ item.updated | date:"M d, Y" }}</p>
  <p class="code-block" id="itemText">{{ item.text }}</p>
  <!-- <textarea rows="3" cols="30" id="itemText">{{ item.text }}</textarea> -->
  <button onclick="copyToClipboard('#itemText')">Copy</button>
  {% if item not in user.userprofile.saved.all %}
  <button>Save</button>
  {% endif %}
  <p class="item-description" ><strong>Description: </strong></br> {{ item.description }}</p>
  <p><strong>Run As: </strong> {{ item.run_as }}</p>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script>
  function copyToClipboard(element) {
    var $temp = $("<textarea>");
    $("body").append($temp);
    $temp.val($(element).text()).select();
    document.execCommand("copy");
    $temp.remove();
  }
</script>

{% endblock %}

templates/library/items.html
{% extends 'base_list.html' %}

{% block content %}
{% block list_title %}<h4>By Category</h4>{% endblock %}
{% block list %}
  {% regroup item_list by category as category_list %}
  <ul>
  {% for category in category_list %}
  <li><h5> id="{{ cateory.pk }}"{{ category.grouper }}</h5>
    <ul>
      {% for item in category.list %}
      {% if item.reviewed %}
      <li>
	      <a href="{% url 'item-detail' pk=item.id %}"><strong>{{ item }}</strong></a></br>
	      <p class="code-block" id="{{ item.pk }}">{{ item.text }}</p>
	      <button onclick="copyToClipboard('#{{ item.pk }}')">copy</button>
      </li>
      {% endif %}

      {% endfor %}
    </ul>
    </li>
  {% endfor %}
  </ul>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script>
  function copyToClipboard(element) {
    var $temp = $("<textarea>");
    $("body").append($temp);
    $temp.val($(element).text()).select();
    document.execCommand("copy");
    $temp.remove();
  }
</script>
{% endblock %}
{% endblock %}

templates/library/languages.html
{% extends 'base_list.html' %}

{% block content %}
{% block list_title %}<h4>By Language</h4>{% endblock %}

{% endblock %}
{% endblock %}

templates/library/types.html
{% extends 'base_list.html' %}

{% block content %}
{% block list-title %}<h4>By Type</h4>{% endblock %}


{% endblock %}

templates/library/userprofile.html
{% extends 'base_generic.html' %}

{% block content %}
{% if user.is_authenticated %}
{% if perms.library.can_add_item %}
{% include "contrib_form.html" %}
{% endif %}
<div class="useritem-lists">
  <div  class="contrib-list">
  {% if contributions %}
  <p><strong>Total Contributions: </strong>  {{ total_contributions }}</p>
  <ul>
  {% for item in new_contrib.all %}
      <li>
       <a href="{% url 'item-detail' pk=item.id %}"><strong>{{ item }}</strong></a></br>
       <p class="code-block" id="{{ item.pk }}">{{ item.text }}</p>
       <button onclick="copyToClipboard('#{{ item.pk }}')">copy</button>
      </li>
  {% endfor %}
  </ul>
{% endif %}
  </div>

<div  class="user-list">
{% if saved_items %}
	<p><strong>Saved: </strong> {{ saved_count }}</p>
<ul>
  {% for item in saved_items.all %}
        <li>
       <a href="{% url 'item-detail' pk=item.id %}"><strong>{{ item }}</strong></a></br>
       <p class="code-block" id="{{ item.pk }}">{{ item.text }}</p>
       <button onclick="copyToClipboard('#{{ item.pk }}')">copy</button>
      </li>
  {% endfor %}
</ul>
{% endif %}
</div>

<div class="pending-list">
{% if pending_contributions %}
  <p><strong>Pending Contributions: </strong> {{ pending_count }}</p>
  <ul>
    {% for item in pending_contributions.all %}
        <li>
       <a href="{% url 'item-detail' pk=item.id %}"><strong>{{ item }}</strong></a></br>
       <p class="code-block" id="{{ item.pk }}">{{ item.text }}</p>
       <button onclick="copyToClipboard('#{{ item.pk }}')">copy</button>
      </li>
    {% endfor %}
  </ul>
{% endif %}
</div>

</div>
{% endif %}

<script>
/* When the user clicks on the button,
toggle between hiding and showing the dropdown content */
function myFunction() {
    document.getElementById("myDropdown").classList.toggle("show");
}
// Close the dropdown if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {

    var dropdowns = document.getElementByid("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}

</script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script>
  function copyToClipboard(element) {
    var $temp = $("<textarea>");
    $("body").append($temp);
    $temp.val($(element).text()).select();
    document.execCommand("copy");
    $temp.remove();
  }
</script>


{% endblock %}